from .detection.code_analysis import *
from .detection.csrf_detection import *
from .detection.directory_indexing_detection import *
from .detection.sql_injection_detection import *
from .detection.xss_detection import *
from .general.crawl_scan import *
from .general.main_page import *
from .general.result_page import *
from .pdf_result.pdf_result import *